### ISSUE TITLE
Need crontab

### ISSUE THREAD

**Issue by jfmatth** [sclorg/s2i-python-container#197]
I have a django app running on Openshift V2 with the cron gear installed, and it's awesome!

I have a need to run cron jobs on a regular basis and right now, I'd like to spin up a new pod with just my django app for cron jobs, but crontab isn't installed, so wondering if that is the best option.

Until the cron option for kubernetes is available.

Thoughts?

**Comment by bparees** [comment]
can you use a Cron Job? 
https://docs.openshift.org/latest/dev_guide/cron_jobs.html

**Comment by jfmatth** [comment]
Ben, thanks for that response.  Yes, I want to use that, but it doesn't seem like it's ready yet?

What version of OS do i need to specify in Minishift to start using cron jobs?

J

**Comment by bparees** [comment]
@soltysh what release were cronjobs in?

**Comment by andrewklau** [comment]
I think they were called ScheduledJobs in 1.4 and then CronJobs in 1.5

**Comment by jfmatth** [comment]
thanks Andrew, i'll give that a try.  I thought CronJob is different than scheduledjob, but i'll see

**Comment by jfmatth** [comment]
OK, so i get that there are cronjobs, but i'm unable to make them work on Minishift

I'm running Minishift v1.1 and OS 1.5.1

```
C:\>oc create -f cronjob.yaml
unable to decode "cronjob.yaml": no kind "CronJob" is registered for version "batch/v2alpha1" [batch/v2alpha1, Kind=Cron
Job]
```

**Comment by soltysh** [comment]
@jfmatth which exact version of openshift you're using, this includes oc client as well. Can you show me your `cronjob.yaml` file. I've been using cronjob in 1.5 without any problems, so I'm not sure what's the exact environment you're using.

**Comment by jfmatth** [comment]
Maciej, 

I love the global nature of this group!  Thank you so much for your response.

Yup, that was it!  My client was still 1.3.  Downloading the newest 1.5 did the trick, and below is the information you asked for just in case.

OC Version
```
C:\openshift>oc version
oc v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.99.100:8443
openshift v1.5.1+7b451fc
kubernetes v1.5.2+43a9be4

```
Source from sample
```
C:\openshift>more cronjob.yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never

C:\openshift>
```

Submitting the job works now (THANK YOU!)
```
C:\openshift>oc create -f cronjob.yaml
cronjob "pi" created
```
